name = input("Give me your name: ")
age  = int((input("Give me your age: ")))
copies  = int((input("Give me your age: ")))
diff = 2018+(100-age)
print(("Hello " + name + ", you will be 100 at: " + str(diff) + "\n") * copies)